### ISSUE TITLE
Management: Prepare Post For Customer Presentation 2

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#437]
According to our meeting, we have prepared scenarios for Customer Presentation 2. I need to prepare posts according to that scenarios. I need to provide title, body, category, image in logical way.

**Comment by BeratDamar** [comment]
We met with @yigit-can-ozkaya and @umutdenizsenerr in presentaion morning in A5. We found some images to use while creating post and we created different  posts and comments to show during customer presentation. We also created a content for chat functionalities. We also created related users to prevent time lost during presentation. 

I guess you can close that issue since it is completed successfully.

Thanks @umutdenizsenerr  and @yigit-can-ozkaya  for your contribution. 💯
